// Refreshes the auto-generated "At a glance" block in README.md from the code.
//   npm run readme
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const walk = (dir) =>
  fs.readdirSync(path.join(root, dir), { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]));

const pkg = JSON.parse(read('package.json'));
const routeFiles = walk('src/modules').filter((f) => f.endsWith('routes.js'));
const endpoints = routeFiles.reduce((n, f) => n + (read(f).match(/^\s*\w+[Rr]outer\.(get|post|put|patch|delete)\(|^\s*router\.(get|post|put|patch|delete)\(/gm) ?? []).length, 0);
const tables = (read('db/schema.sql').match(/CREATE TABLE/g) ?? []).length;
const modules = fs.readdirSync(path.join(root, 'src/modules')).length;
const tests = walk('tests').filter((f) => f.endsWith('.test.js')).reduce((n, f) => n + (read(f).match(/^\s*(it|test)\(/gm) ?? []).length, 0);
const jobs = (read('src/jobs/index.js').match(/^\s*cron\.schedule/gm) ?? []).length;
const deps = Object.keys(pkg.dependencies).length;

const card = (value, label) => `<td align="center"><h2>${value}</h2>${label}</td>`;
const block = `<!-- STATS:START -->
<table>
  <tr>
    ${card(endpoints, 'REST endpoints')}
    ${card(tables, 'DB tables')}
    ${card(modules, 'API modules')}
    ${card(tests, 'automated tests')}
    ${card(Math.round(jobs), 'background jobs')}
    ${card(deps, 'runtime deps')}
  </tr>
</table>
<sub>Generated by <code>npm run readme</code> from the source on ${new Date().toISOString().slice(0, 10)}.</sub>
<!-- STATS:END -->`;

const file = path.join(root, 'README.md');
const md = fs.readFileSync(file, 'utf8');
if (!md.includes('<!-- STATS:START -->')) throw new Error('STATS markers missing in README.md');
fs.writeFileSync(file, md.replace(/<!-- STATS:START -->[\s\S]*<!-- STATS:END -->/, block));
console.log({ endpoints, tables, modules, tests, jobs, deps });
